### ISSUE TITLE
Logo, Final

### ISSUE THREAD

**Issue by bam32099** [IDM-SP-2021/afiye#62]

**Comment by bb837** [comment]
How would you like this logo? (ie a pdf with just the logos?,  or the whole brand guide exported as pdf file,  do you want it a specific size?)

**Comment by bam32099** [comment]
> How would you like this logo? (ie a pdf with just the logos?, or the whole brand guide exported as pdf file, do you want it a specific size?)

On Rob's Blackboard, he specifies the following...
Submit a single ZIP file with Adobe Illustrator AI files.
Your final logos, in vector format. These will be used directly in department promotional material.
Include all variations, (1-color, 2-color, etc) either as named groups in one AI file or as clearly named individual AI files. 
Make sure your team name is in the filenames. 
No generic filenames!

Must Include: Team Logo & Project Logo
1 point per logo, 2 points total.
If your team and project logo will be the same, make that clear in your submission.


Besides what Rob wanted above, there are no other requirements.

**Comment by bb837** [comment]
it is submitted
